### ISSUE TITLE
Title "Therapy – non-medicinal"  To  Title "Therapy - lifestyle changes"

### ISSUE THREAD

**Issue by ghumman96** [OHSUCMP/coach#100] opened 2023-10-20 17:04 UTC
Hello Amy, 

This was brough up during AB meeting. Can you please change Therapy non-medicinal to Therapy - lifestyle changes.

Approved by team.

Aisha

**Comment by mattStorer** [comment] 2023-10-20 18:03
closing as this is a duplicate of #99

**Closed by mattStorer** 2023-10-20 18:03 UTC
